name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Dart format (check)
        run: dart format --output=none --set-exit-if-changed .

      - name: Dart analyze
        run: dart analyze

      - name: Flutter tests
        run: flutter test

      - name: Policy gate (tasks.yaml)
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyyaml
          python3 tools/policy_check.py
